name: Publish WASM version

on:
  push:
    branches:
      - main

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - name: Build
        run: go build -o site/gumpjam.wasm .
        env:
          GOOS: js
          GOARCH: wasm
      - name: Copy wasm_exec.js
        run: cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" site/
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.4.3
        with:
          branch: gh-pages
          folder: site
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}